### ISSUE TITLE
segfault with \n filled map file

### ISSUE THREAD

**Issue by krozis** [krozis/42_Cub3D#1]
## Expected Behavior
  Print an Error message:
```
Error
Invalid configuration file
```
## Current Behavior
`Segfault`

## Possible Solution
check if empty lines

## Steps to Reproduce
`./cub3D map.cub`
with a file map.cub filled only with some \n

**Comment by dcyprien** [comment]
fixed in commit 9f95c2f6fa93b0fbb8a155ceb2edefaedfe2a65d
