### ISSUE TITLE
infinite loop with some map files

### ISSUE THREAD

**Issue by krozis** [krozis/42_Cub3D#2]
## Expected Behavior
  Print an Error message:
```
Error
Invalid configuration file
```
## Current Behavior
 Infinite loop

## Possible Solution
Check lines to see if full of printable char or just zero filled

## Steps to Reproduce
`ln -s /dev/random random.cub`
`./cub3D random.cub`
and/or
`ln -s /dev/zero random.cub`
`./cub3D zero.cub`

**Comment by dcyprien** [comment]
/dev/zero and /dev/ranom are "infinite" files. Behavior is coherent with code and fixing it exposes code to more bug.
